#!/bin/sh

prepare()
{
	for item in /etc/multiboot.d/01-Maemo-kernel-power[0-9][0-9].item
	do
		echo "Removing ${item}"
		rm -f ${item}
	done

	for kernel in /boot/multiboot/vmlinuz-2.6.28.10power[0-9][0-9]
	do
		echo "Removing ${kernel}"
		rm -f ${kernel}
	done
}


case "$1" in

    remove|upgrade)
	prepare
	;;

    failed-upgrade|deconfigure)
	;;

    *)
	echo "prerm called with unknown argument $1" >&2
	exit 1
	;;

esac

